"""candidate_publication

Revision ID: 0004
Revises: 0003
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved', sa.JSON(), nullable=False),
    sa.Column('needs_attention', sa.Boolean(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.CheckConstraint("status IN ('READY', 'NEEDS_INFO', 'REJECTED', 'DISCUSSION', 'REVIEW', 'PUBLISHED', 'DISMISSED')", name=op.f('ck_action_candidates_status')),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_action_candidates_analysis_id_analyses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_candidates')),
    sa.UniqueConstraint('analysis_id', 'position', name=op.f('uq_action_candidates_analysis_id'))
    )
    op.create_index('ix_action_candidates_needs_attention', 'action_candidates', ['needs_attention'], unique=False)
    op.add_column('tasks', sa.Column('candidate_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_tasks_candidate_id'), 'tasks', ['candidate_id'])
    op.create_foreign_key(op.f('fk_tasks_candidate_id_action_candidates'), 'tasks', 'action_candidates', ['candidate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_candidate_id_action_candidates'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('uq_tasks_candidate_id'), 'tasks', type_='unique')
    op.drop_column('tasks', 'candidate_id')
    op.drop_index('ix_action_candidates_needs_attention', table_name='action_candidates')
    op.drop_table('action_candidates')
    # ### end Alembic commands ###
