"""processing_scope

Revision ID: 0005
Revises: 0004
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('scope', sa.String(length=30), server_default='ANALYSIS_ONLY', nullable=False))
    op.create_check_constraint(op.f('ck_processing_jobs_scope'), 'processing_jobs',
                               "scope IN ('ANALYSIS_ONLY', 'FULL_PIPELINE')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_processing_jobs_scope'), 'processing_jobs', type_='check')
    op.drop_column('processing_jobs', 'scope')
    # ### end Alembic commands ###
